---
defaults:
  - scope:
      path: ""
      type: home
    values:
      layout: home
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
# - scope:
#     path: "" # any file that's not a post will be a "page" layout by default
#   values:
#     layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - "*.gemspec"
  - "*.toml"
  - "*.yml"
  - "*.yaml"

plugins:
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-spaceship
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-remote-theme

readme_index:
  remove_originals: true
  with_frontmatter: true

jekyll-archives:
  enabled: all

# jekyll-feed
title: USTC iVC Lab
author: ustcivclab
description: Homepage for USTC iVC Lab
url: https://ustcivclab.github.io

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  people:
    - faculty: tag/faculty
    - students: tag/student
    - alumni: tag/alumni
  publications:
    - papers: pages/papers
    - patents: pages/patents
  activities:
    - academic activities: tag/academic
    - entertainment: tag/entertainment
  services:
    - publication list: tag/resources


  #tags: tag

## navbar-links:
##   publications:
##     - papers: tag/publication
##     - patents: tag/publication
##   news:
##     - publications: tag/publication
##     - activities: tag/activity
##     - topics: tag/topic
##   people:
##     - faculty: tag/faculty
##     - students: tag/student
##     - alumni: tag/alumni
##   tags: tag


  #more: README

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: fanye@mail.ustc.edu.cn
  rss: true
  github: ustcivclab

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: https://avatars.githubusercontent.com/u/116997363

###########################
# --- General options --- #
###########################

# Excerpt word length - Truncate the excerpt of each post on the feed page to
# the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: false

# Add a button in the footer to edit the current page. Only works if your
# website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than
# the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the
# issue this setting can solve
navbar-var-length: false
